language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install .


# command to run tests
script:

jobs:
  include:
  - stage: Linting
    env:
      - LABEL=flake8
    script:
      - make flake8-check

  - stage: Linting
    env:
      - LABEL=pyre
    script:
      - make pyre-check

  - stage: Linting
    env:
      - LABEL=docstyle
    script:
      - make pydocstyle-check

  - stage: Installation
    script:
      - pip install .

  - stage: Testing
    env:
      - LABEL=functional-tests
    script:
      - make functional-tests

  - stage: Testing
    env:
      - LABEL=unit-tests
    script:
      - make unit-tests

  # Tags are created on each succesful merge of a pull request.
  - stage: Tagging
    branches: master
    script:
      - make new-tag
      - make push-tag


deploy:
  provider: pypi
  user: nlsdfnbch
  password: <encrypted>
  on:
    tags: true
  distributions: "bdist_wheel"
  skip_existing: true
  after_deploy:
    - make commit-wheel

stages:
  - Linting
  - Installation
  - Testing
  - name: Tagging
    if: branch = master
  - name: Release
    if: branch = master
